Repository PixelsCamp/talks, pull requests merged in 2019-02, with the labels that each got.

#253 From zero to Continuous Delivery in 6 months
  from-zero-to-continuous-delivery-in-6-months_joao-malcata.md
Labels: pre-accepted

#254 AGILE WARS
  agile-wars_nuno-pereira.md
Labels: half-length, multiple submissions, pre-accepted

#250 Journey to Mars
  journey-to-mars_kartik-kumar.md
Labels: pre-accepted

#286 The Future of Fonts
  The-Future-Of-Fonts_Natanael-Gama
Labels: connections, past deadline, pre-accepted

#279 Design microservices for resilience
  designing-microservices-for-resilience-Nuno-Caneco.md
Labels: pre-accepted, reviewing

#278 Struggling with AWS
  2019/struggling-with-aws_gabriel-poca.md
Labels: pre-accepted, reviewing

#249 How to build your own greenfield?
  how-to-build-your-own-greenfield_mario-goncalves.md
Labels: pre-accepted

#247 Quantum Supremacy
  quantum-supremacy_miguel-sozinho-ramalho.md
Labels: double-length, multiple submissions, pre-accepted, workshop

#238 How Programming Can Save A Biologist's Life
  How-Programming-Can-Save-A-Biologists-Life_Beatriz-Costa-Gomes
Labels: pre-accepted

#237 Living on the Edge — Cloudflare Workers
  living-on-the-edge-cloudflare-workers_hugo-romano.md
Labels: pre-accepted

#234 Emoji Board - A Quick Elixir Showcase
  emoji-board-a-quick-elixir-showcase_filipe-cabaco.md
Labels: multiple submissions, pre-accepted

#273 Embracing Elixir: An Adoption Story
  embracing_elixir_at_onfido-daniel_caixinha.md
Labels: pre-accepted

#263 KDD: Kubernetes Driven Development
  kubernetes-driven-development_ricardo-castro.md
Labels: pre-accepted

#280 Progressive Web App: From Full Online to Full Offline
  2019/PWA_From_Full_Online_to_Full_Offline_Ricardo_and_Domingos.md
Labels: double-length, pre-accepted, workshop

#294 The Future of Ethereum UX
  2019/the-future-of-ethereum-ux.md
Labels: connections, past deadline, pre-accepted, reviewing

#202 Everyone is naked: attacking the DHT
  2019/everyone_is_naked_attacking_the_dht-goncalo_pestana.md
Labels: pre-accepted

#203 An intro to Mutation Testing - or why coverage sucks
  mutation-testing_pedro-rijo.md
Labels: pre-accepted

#205 Build Fast & Make Things
  build-fast-and-make-things_nader_dabit.md
Labels: needs changes, pre-accepted

#223 <3 WebGL
  love-webgl_hugo-gomes.md
Labels: pre-accepted

#217 Graph Neural Networks — when magic meets structure
  graph-neural-networks-when-magic-meets-structure_presenter-name.md
Labels: pre-accepted

#211 Mob programming to deliver better software
  mob-programming_joao-fernandes.md
Labels: pre-accepted

#207 Shipping Better Software Faster and Having Fun Doing It
  shipping-better-software-faster-and-having-fun-doing-it_chris-holland.md
Labels: multiple submissions, pre-accepted

#212 The universal serial web
  the_universal_serial_web.md
Labels: pre-accepted

#219 AI-powered Data Model Design
  ai-powered-data-model-design.md
Labels: pre-accepted

#221 AWS API Gateway with Terraform
  AWS-API-Gateway-with-Terraform_Ricardo-Brazao.md
Labels: pre-accepted

#220 Building Your First React App
  building-your-first-react-app_jose-sousa.md
Labels: pre-accepted, workshop

#228 Recognizing Content vs Pub in Live TV
  content-vs-pub_alexandre-carvalho.md
Labels: pre-accepted

#230 The Block Power
  the-block-power_bernardo-vieira.md
Labels: pre-accepted, workshop

#231 Right to Repair (fix your broken device!)
  right-to-repair_luis-correia.md
Labels: pre-accepted

#283 From product design to product design
  from-product-design-to-product-design_nuno-loureiro.md
Labels: connections, past deadline, pre-accepted

#216 FONK - A Serverless Stack for Kubernetes
  FONK_A_Serverless_Stack_for_Kubernetes-Julio_Gomez.md
Labels: pre-accepted

#210 Going Arabic
  Going-Arabic_Gil-Faria.md
Labels: pre-accepted

#251 Build a Vue.js application from scratch
  build-a-vue-app-from-scratch.md
Labels: double-length, pre-accepted, workshop

#281 Using Java Microbenchmark Harness
  2019/using-java-microbenchmark-harness_samuel-campos.md
Labels: pre-accepted

#274 Text, Computers and Python
  text-computers-and-python_tiago-montes.md
Labels: pre-accepted

#291 VR Design : Designing Aplications for motion
  VR-Design-Designing-Aplications-for-motion_ricardo-almeida.md
Labels: connections, past deadline, pre-accepted

#296 GitOps - Operations done through git
  2019/gitops-operations-done-through-git_luis-faceira.md
Labels: connections, meetup, past deadline, pre-accepted

#218 Pushing HTML Canvas to the Limit
  pushing-html-canvas-to-the-limit_luis-cardoso.md
Labels: pre-accepted

#224 Ready, Set, Flutter
  ready-set-flutter_filipe-barroso.md
Labels: pre-accepted

#264 Survival Guide to Information Retrieval
  survival-guide-to-information-retrieval-the-quest-to-find-the-golden-goose-with-golden-shoes_jose-marcelino.md
Labels: pre-accepted

#242 Penalty-free multiplatform programming with Kotlin
  penalty-free_multiplatform_programming_with_kotlin.md
Labels: pre-accepted

#289 a11y, who?
  2019/a11y-who_cristiano-correia.md
Labels: connections, past deadline, pre-accepted

#292 Deploying the Internet of Things
  Deploying-the-Internet-of-Things_Jose-Marcelino.md
Labels: connections, past deadline, pre-accepted

#293 Women in DevOps
  Women-in-DevOps_Cristina-Moura-Rebelo.md
Labels: connections, meetup, past deadline, pre-accepted

#282 IoT - Introduction to home automation
  iot-intro-to-home-automation_pedro-januario.md
Labels: past deadline, pre-accepted

#287 Stack my JAM up!
  smack-my-jam-up_nuno-pereira.md
Labels: connections, past deadline, pre-accepted

#260 Information Security 101
  Information-Security-101_Basilio-Vieira.md
Labels: pre-accepted

#248 Will you take that API to GO?
  will-you-take-that-api-to-go_tiago-mendes.md
Labels: pre-accepted

#246 Unravelling the Web of Things: Exploring Mozilla Things Framework
  unravelling-the-web-of-things_joao-pedro-dias.md
Labels: pre-accepted, workshop

#214 Utility-First CSS: Build a clean Component based system
  utility-first-css-build-a-clean-component-based-system.md
Labels: pre-accepted

#215 Augmented Reality: What, how and why?
  Augmented-Reality-What-how-and-why_António_Lima.md
Labels: pre-accepted

#222 Adaptive Image Loading for Best Performance
  adaptive-image-loading-for-best-performance_tamas-piros.md
  talk-title_presenter-name.md
Labels: pre-accepted, workshop

#245 Grab your helmets for some Extreme Programming
  grab-your-helmets-for-some-extreme-programming_Ana-Machado-and-Bruno-Areal.md
Labels: pre-accepted

#213 Unlocking ultimate productivity between engineers and designers
  Unlocking-ultimate-productivity-between-engineers-designers_Maria-Margarida-Silva.md
Labels: pre-accepted
