Repository PixelsCamp/talks, pull requests merged in 2019-03, with the labels that each got.

#241 you. and the morals of technology
  you-and-the-morals-of-technology_fernando-mendes.md
Labels: pre-accepted

#204 Everything You Always Wanted to Know About Product Managers*
  everything-you-always-wanted-to-know-about-product-managers_joao-craveiro.md
Labels: pre-accepted

#240 Bootstrapping your indie business
  2019/bootstrapping-your-indie-business_paulo-andrade.md
Labels: pre-accepted

#285 Containers 101
  2019/containers-101.md
Labels: past deadline, pre-accepted

#284 Reactive React - The Observable Way
  reactive-react-the-observable-way_joao-pinho.md
Labels: past deadline, pre-accepted

#297 Beyond Code: thinking "right" to become a better Engineer
  beyond-code_rodrigo_goncalves.md
Labels: past deadline, pre-accepted

#295 Quantiles over Percentiles: When and How
  2019/quantiles-over-percentiles_joao-acabado.md
Labels: connections, meetup, past deadline, pre-accepted

#233 More Tests, Less Work
  more_tests_less_work-luis_rodrigues-miguel_duarte
Labels: pre-accepted

#299 OWASP Juice Shop - First you :-D:-D then you :,-(
  2019/owasp-juice-shop_bjoern-kimminich.md
Labels: connections, past deadline, pre-accepted

#301 Geo-distributed applications with Serverless Architectures and CosmosDB
  2019/geo-distributed-applications-with-serverless-architectures-and-cosmosdb_tiago-barbosa.md
Labels: connections, past deadline, pre-accepted

#302 Pixels vs. Juice Shop
  2019/pixels-vs-juice-shop_bjoern-kimminich.md
Labels: past deadline, workshop
