Repository PixelsCamp/talks, pull requests merged in 2020-02, with the labels that each got.

#405 Machine that goes Ping: Low Power Sensor nodes with Python
  machine_that_goes_ping-jose_marcelino.md
Labels: double-length, past deadline, pre-accepted, workshop

#404 Do you even (Kotlin) Flow? The new API for reactive programming
  do-you-even-kotlin-flow_ricardo-costeira.md
Labels: pre-accepted

#398 Beyond REST: GraphQL vs gRPC Web
  beyond-rest-graphql-vs-grpcweb_yury-kozyrev.md
Labels: pre-accepted

#388 Developing Applications for Smart TVs
  developing-applications-for-smart-tvs_david-silva.md
Labels: pre-accepted

#366 Embracing Simplicity
  embracing-simplicity_guilherme-ferreira.md
Labels: pre-accepted

#313 What the Service Mesh?!
  what-the-service-mesh_ricardo-castro.md
Labels: multiple submissions, pre-accepted

#314 Testing practices for mobile
  testing-practices-for-mobile_Douglas_Ritter.md
Labels: pre-accepted

#316 Meet the natives: from compilation to execution
  meet-the-natives_joao_sampaio.md
Labels: pre-accepted

#317 How to defeat imposter syndrome: confessions of a developer
  how-to-defeat-imposter-syndrome-confessions-of-a-developer_matteo-bruno.md
Labels: pre-accepted

#318 2600 Hz
  2600-hz_celso_martinho.md
Labels: connections, pre-accepted

#320 Aiming for delight in Customer Experience
  aiming-for-delight-in-customer-experience_bruno-cruz.md
Labels: pre-accepted

#321 Accounting data in P2P-blockchain
  accounting-jobs_nuno-saraiva.md
Labels: pre-accepted

#323 webauthn: a better alternative for securing webapps
  webauthn-a-better-alternative-for-securing-webapps_paulo-lopes.md
Labels: pre-accepted

#324 A Tour of ActivityPub
  a-tour-of-activitypub_diogo_cordeiro.md
Labels: pre-accepted

#325 Building a mobile decentralised game using JS
  building-a-mobile-decentralised-game-using-js-pedro-teixeira.md
Labels: pre-accepted

#328 v2.0: Monoliths, Microservices and Startups' horrible code
  talk-UnbabelArchitecture2.0_Miguel_Filipe.md
Labels: pre-accepted

#329 Distributed Monoliths
  distributed_monoliths_joao_vasques.md
Labels: pre-accepted

#332 A trip down Docker build history to BuildKit
  A-trip-down-Docker-build-history-to-BuildKit_Fernando_Miguel.md
Labels: half-length, pre-accepted

#333 Javascript Will Kill You
  javascript-will-kill-you_joao-henrique.md
Labels: multiple submissions, pre-accepted

#335 Create a brand for your project that doesn't suck
  create-a-logo-design-for-your-project-that-doesn-t-suck.md
Labels: pre-accepted

#336 Web Animations
  web-animations_rafael-ramalho.md
Labels: pre-accepted

#338 Machine Learning at the Edge
  machine-learning-at-the-edge_claudio-teixeira.md
Labels: pre-accepted

#339 The Boeing 737 MAX - Human Factors in Complex Systems
  the-boeing-737-max_kyle-kotowick.md
Labels: pre-accepted

#340 Cautionary Tales for Geeks
  cautionary_tales_for_geeks_antoniolopes.md
Labels: pre-accepted

#341 From euros to zero: using Probabilistic Data Structures to reduce costs
  from-euros-to-zero_joao-neves-and-paulo-serrao.md
  img/Joao Neves_short_wback.jpg
  img/paulo_serrao.jpg
Labels: pre-accepted

#343 Do I know you? Identity on the Internet and the Question of Trust
  do-i-know-you_kevin_goldsmith.md
Labels: multiple submissions, pre-accepted, restricted availability

#345 The Dark Side of PR - for devs & startups
  the-dark-side-of-pr_Vitor-Domingos.md
Labels: half-length, pre-accepted

#346 The State of NoSQL in 2020
  the-state-of-nosql-in-2020_denis_rosa.md
Labels: pre-accepted

#347 Building a Flight Tracker
  building-a-flight-tracker_joao_carvalho.md
Labels: pre-accepted

#348 Cryptography Gone Wrong
  cryptography-gone-wrong_mathis-hammel.md
Labels: pre-accepted, restricted availability

#349 Non blocking applications with Spring Webflux
  non-blocking-applications-with-spring-webflux_tiago-pires-tiago-batista.md
Labels: pre-accepted

#353 React Hooks broke my tests, now what?
  react-hooks-broke-my-tests-now-what_daniel_afonso.md
Labels: pre-accepted

#355 Egoless Programming
  egoless-programming_andre_jonas.md
Labels: pre-accepted

#356 Taming giants, one test at a time
  taming-giants-one-test-at-a-time_luis_correia.md
Labels: multiple submissions, pre-accepted

#357 PWAs and Fighting Against App Stores
  pwas-and-fighting-against-app-stores_gabriel_poca.md
Labels: pre-accepted

#358 AST Transformations For Fun & Profit
  ast-transformations-for-fun-and-profit_noam-tenne.md
Labels: multiple submissions, pre-accepted

#351 We Need A Better Testing Framework
  we-need-a-better-testing-framework_noam-tenne.md
Labels: approval blocked, multiple submissions

#359 Internal-Facing Products Don't Have to Be Bad
  internal-facing-products-dont-have-to-be-bad_joao-craveiro.md
Labels: pre-accepted

#360 Processing Text with Machine Learning
  Processing-Text-with-Machine-Learning_Fabian-Reich.md
Labels: pre-accepted

#361 Murphy's Law in the IoT Age
  murphys-law-in-the-iot-age_joao-pedro-dias.md
Labels: pre-accepted

#367 Edge Computing of Today
  edge-computing-of-today_hugo-romano.md
Labels: meetup, pre-accepted

#362 Flutter Workshop
  flutter-workshop-by-flutterportugal_daniel-jorge
Labels: double-length, meetup, pre-accepted, workshop

#364 Blockchain in your project — you don't need it, unless you don't have a choice
  why-you-dont-need-a-blockchain_kirill-pimenov.md
Labels: pre-accepted

#368 So you want to be a manager
  So-you-want-to-be-a-manager_Gil-Goncalves.md
Labels: pre-accepted

#369 How solid RocksDB really is?
  how-solid-rocksdb-really-is_nuno-diegues-and-luis-alves.md
Labels: pre-accepted

#363 Automating your Way to Confidence
  automating-your-way-to-confidence_miguel-palhas.md
Labels: pre-accepted

#370 Agile and Marketing, climbing the Tower of Babel
  agile-and-marketing-climbing-the-tower-of-babel_bruno-amaral.md
Labels: pre-accepted

#371 Svelte, cybernetically enhanced web app
  svelte-cybernetically-enhanced-web-app_devlin-duldulao.md
Labels: pre-accepted, restricted availability

#373 Saving the bees with IoT and Elixir
  saving-the-bees-with-iot-an-elixir_jose_resende.md
Labels: pre-accepted

#375 Are we paying attention to what we building?
  are-we-paying-attention-to-what-we-are-building_lawrence-braun.md
Labels: pre-accepted

#377 Sandboxing in Linux with zero lines of code
  sandboxing-in-linux-with-zero-lines-of-code_ignat-korchagin.md
Labels: multiple submissions, pre-accepted

#378 JAMstack Maps
  JAMstack-Maps_Migsar-Navarro.md
Labels: meetup, multiple submissions, pre-accepted

#380 Product Managers, to pair or not to pair?
  pairing-for-product-managers_mihaela-draghici.md
Labels: pre-accepted, restricted availability

#381 Connecting the Dots: a deep dive into Graph Databases
  connecting-the-dots_sofia-gomes.md
Labels: pre-accepted

#382 Twitter Bot Hunting
  twitter-bot-hunting_miguel-sozinho-ramalho.md
Labels: pre-accepted

#383 Ethical Software Development
  ethical-software-development_antonio-almeida.md
Labels: pre-accepted

#385 Let’s get lazy with React
  react-suspense_ricardo-soares-silva.md
Labels: double-length, multiple submissions, pre-accepted, workshop

#387 My journey into Bioinformatics
  my-journey-into-bioinformatics_bruno-vieira.md
Labels: pre-accepted

#389 Terraforming cloud cubed worlds - with one-liners and whimsy
  terraforming-cubed-worlds_joao-anes.md
Labels: pre-accepted

#391 Demystifying the Tribe Model
  demystifying-the-tribe-model_cristiano-correia.md
Labels: meetup, multiple submissions, pre-accepted

#392 Doing Open Source as a contributor and a maintainer
  doing-open-source-as-a-contributor-and-a-maintainer_isabel-costa.md
Labels: pre-accepted

#393 Hooking up with React Hooks
  hooking-up-with-react-hooks_joao_dias_mickael_santos.md
Labels: double-length, pre-accepted, workshop

#401 Hyperledger Fabric 2.0 Workshop
  Hyperledger Fabric 2.0 Workshop.md
Labels: multiple submissions, pre-accepted, workshop
