Repository PixelsCamp/talks, pull requests merged in 2020-03, with the labels that each got.

#394 Sharing is Daring
  sharing-is-daring_mario_goncalves.md
Labels: pre-accepted

#395 Liberating Structures: Transform how people interact and work together!
  transform-how-people-interact-and-work-together-start-using-liberating-structures_nuno-pereira.md
Labels: double-length, meetup, pre-accepted, workshop

#407 I have Failed is the new I have a start-up
  IhavefailedisthenewIhaveastartup_Sonia_Fernandes.md
Labels: connections, past deadline, pre-accepted

#409 Deployment pipeline for databases
  deployment-pipeline-for-databases_eduardo_piairo.md
Labels: meetup, multiple submissions, pre-accepted

#415 Startups are hard, I can't wait to do it again
  Startups are hard I cant wait to do it again_Tiago Henriques.md
Labels: connections, past deadline, pre-accepted

#417 LiveQuiz: Building a rich, real-time webapp without JS
  live_quiz-daniel_caixinha.md
Labels: connections, double-length, meetup, past deadline, pre-accepted, workshop

#419 Ubuntu Portugal Meetup: Join the crew!
  Ubuntu-Portugal-win-a-free-application_tiago-carrondo.md
Labels: connections, meetup, past deadline, pre-accepted, workshop

#421 Continuous Development for Machine Learning - CD4ML
  continuous-development-for-machine-learning_DSPT_SamHopkins.md
Labels: connections, meetup, past deadline, pre-accepted

#422 Introduction to Hardware Development
  introduction-to-hardware-development_Afonso_Muralha.md
Labels: connections, past deadline, pre-accepted
